### PR TITLE
feat(#195): add a distance publisher for the stop line and next waypoint

### LINKED ISSUE #195: [Feature]: create nodes to publish distance and road option of next global way point and distance to next intersection
### Description

To detect the distance to the next intersection in the decision tree, a topic is needed that provides that information. The next intersection can be identified by the global way point with the roadoption "TURNLEFT, TURNRIGHT, STRAIGHT". To also identify the end of the intersection, the next waypoint is needed as it must lie behind the intersection.

### Definition of Done

have to topics publishing the needed information, update information when way point has been reached.

### PR DESCRIPTION
**Pull request by JoKircher**
# Description

Old description: Adds two publisher for the distance to the stop line of an intersection and the next way point. The stop line is indicated by the way point before the intersection. This will be used by the decision tree.

New description: Adds two publisher for the distance to the stop line of an intersection and the distance to the next planned lane change. The behaviour for approaching and entering an intersection is optimized. The behaviour before approaching and entering a lane change was added to the behaviour tree and also optimized.
The behaviour with the Lidar sensor is implemented. To check if we can enter an intersection and enter a lane change event, the distance is checked through the Lidar topic. 
The stop line behaviour is implemented. There is no extra topic which publishes the distance to the next stop sign because the xodr file "signal" part only refers to ground truth traffic sign position data which cannot be used. The agent stops before every intersection and every possible traffic sign to check for other cars. Because of that the stop sign behaviour is also covered in this PR.

For testing the environment was switched to the dev environment (town 12). 

## Time invested

Josef Kircher: 3 h
Simon Erlbacher: 15 h
Niklas Vogel: 15h

## Type of change

Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality)

## Does this PR introduce a breaking change?

Approved decision making with all current informations.

- intersection behaviour
- lane change bahaviour
- distance publisher
- integrated lidar topics
- optimized parameter for agent behaviours

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works (might be obsolete with CI later on)
- [x] New and existing unit tests pass locally with my changes (might be obsolete with CI later on)

### CODE REVIEW

**Comment by JoKircher** [comment]
After merging #154 in this branch more testing was conducted, however there are still some things that need to be fixed.

3 h are added to this PR in this sprint.

**Review by timdreier — APPROVED** [review]
Just tested it, works great! :) Maybe some documentation about this topic would be great!

Is it intended that this PR contains at least #211? If yes, we should keep in mind that we have to review / merge this issue first.

Furthermore it seems like the car runs very fast. Is this intended?

Time to test and review 30 min

**Comment by JoKircher** [comment]
> Just tested it, works great! :) Maybe some documentation about this topic would be great!
> 
> Is it intended that this PR contains at least #211? If yes, we should keep in mind that we have to review / merge this issue first.
> 
> Furthermore it seems like the car runs very fast. Is this intended?
> 
> Time to test and review 30 min

There is another branch(#215) incorporation #211 and this branch to do some integration tests. In this branch the velocity tuning is done as well.

**Review by JoKircher — COMMENTED** [review]
New changes seem to break this PR. This PR should have been merged separately and a new PR should have been created for the work done in #215

**Pull request merged**
