### PR TITLE
194 feature decision tree implement stopping behavior

### LINKED ISSUE #194: [Feature]: decision tree - implement stopping behavior
### Description

The needed behaviors are already there but the functionality is missing. This behavior is similar to the intersection behavior, but the ego vehicle has to stop in front of the intersection and wait for the intersection to be cleared by crossing traffic.

As testing is limited right now, some more adjustments will be needed in the future.

### Definition of Done

- all behaviors in the subtree should be reached and executed in the right order

### PR DESCRIPTION
**Pull request by JoKircher**
# Description

To also handle stop signs the intersection behavior is extended. If a stop sign is detected and no traffic light is recognized, just like in the real world where a traffic light has a higher priority than a stop sign, the agent has to wait in front of the intersection. There is also a new mock topic `intersection_clear` that indicates that we can drive through the intersection. This is only necessary if there is a stop sign, as we can drive through the intersection only if there is no other traffic.

please note that this PR will only be merged after #192, and should be reviewed after that one as there are many redundant changes

Fixes #194 

## Time invested

Josef: 5 h

## Type of change

Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality)

## Does this PR introduce a breaking change?
no

## Most important changes

intersection.py

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works (might be obsolete with CI later on)
- [x] New and existing unit tests pass locally with my changes (might be obsolete with CI later on)

### CODE REVIEW

**Comment by JoKircher** [comment]
This is now ready for review

**Review by vogelnik — CHANGES_REQUESTED** [review]
The code additions look good and logical as far as i can tell. Also the documentations are very helpful. But when i tried to test it myself i experienced some issues:

- the behavior agent dies when entering the intersection:
image

- the infos i get on the console make it look like the program is working fine but the car does not follow these instructions in the simulation (like slowing down or stoping)

- the branch is not up to date with main -> topic names etc not up to date (maybe thats the reason why the car doesnt follow the instructions)

**Review by erlbacsi — APPROVED** [review]
The mock publisher for testing are a nice idea and good to understand how the decision making works. The approaching of the intersections is wokring and slowing down the speed of the agent. This of course has to be tested with the agent itself. 
I don't have to add any changes. This has to be tested in dev environment and the leaderboard as mentioned above. The logic of the intersection and stopping scenario was clear to me.
Review time: 50min (familiarize with the topic)

**Comment by JoKircher** [comment]
This PR can be merged and when the main branch is ready, it can be put into #197. For now, I have worked on that branch independently, bc it was testable. The additions in this PR shouldn't have too many changes compared to #197.

**Review by vogelnik — APPROVED** [review]

**Pull request merged**
