### PR TITLE
131 feature implement filter for the gps sensor

### LINKED ISSUE #131: [Feature]: Implement filter for the GPS sensor
### Description

The current implementation of the GPS signal is too noisy for the lateral control algorithms.
A filter of some sort needs to be implemented.
With current methods (simple average) not working, a dedicated effort should be made to the processing of the sensor data.

### Definition of Done

- sensor data should be useable for lateral control
- move code from `DummyTrajectorySub.py` to a dedicated file
- Add documentation for the entire issue

### PR DESCRIPTION
**Pull request by schwalga**
# Description

This PR starts to deal with the problem of the noisy GPS sensor. For now, I moved all the code concerned with publishing the current position to a dedicated file. I also took a look at different filter options. At the moment an extended Kalman filter is a likely option, although things might change.
In the end, I will also update the documentation based on the new implementation.
Fixes #131 

## Time invested

- 4h @schwalga 

## Type of change

Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality)

## Does this PR introduce a breaking change?

No

## Most important changes

Most of the work will be handled within the new node `PublishPosition.py`.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works (might be obsolete with CI later on)
- [x] New and existing unit tests pass locally with my changes (might be obsolete with CI later on)

### CODE REVIEW

**Comment by schwalga** [comment]
We have integrated the [EKF](https://github.com/udacity/robot_pose_ekf) node.
We also updated the way in which the heading is calculated.
Encountered some issues along the way, but the current_pos topic should be accurate enough to be used for steering.
Unfortunately, it did not have enough time to test the latest version with a steering controller.

- 7h by @Julian-Graf 
- 10h by @schwalga

**Review by vogelnik — APPROVED** [review]
I dont get why it shows the changes to the docker compose-/taskfile with nvidia, gpu... as your changes cause i thought that was already pushed to main by #125. Please take care about this one when merging so that it cannot cause trouble later on.

However the rest of your code looks like great work for me and it ran without issues when i tried testing it. (I couldnt test how good of a improve your filter is but probably you will show us in sprint review anyway)

Please take care of the merge conflict in the Dockerfile that is shown by github before merging!

review time 1h

**Comment by Julian-Graf** [comment]
> I dont get why it shows the changes to the docker compose-/taskfile with nvidia, gpu... as your changes cause i thought that was already pushed to main by #125. Please take care about this one when merging so that it cannot cause trouble later on.
> 
> However the rest of your code looks like great work for me and it ran without issues when i tried testing it. (I couldnt test how good of a improve your filter is but probably you will show us in sprint review anyway)
> 
> Please take care of the merge conflict in the Dockerfile that is shown by github before merging!
> 
> review time 1h

You saw these already pushed changes to the docker compose-/taskfile, because this branch was behind main. Should be fixed now

**Comment by vogelnik** [comment]
> > I dont get why it shows the changes to the docker compose-/taskfile with nvidia, gpu... as your changes cause i thought that was already pushed to main by #125. Please take care about this one when merging so that it cannot cause trouble later on.
> > However the rest of your code looks like great work for me and it ran without issues when i tried testing it. (I couldnt test how good of a improve your filter is but probably you will show us in sprint review anyway)
> > Please take care of the merge conflict in the Dockerfile that is shown by github before merging!
> > review time 1h
> 
> You saw these already pushed changes to the docker compose-/taskfile, because this branch was behind main. Should be fixed now

Perfect thanks now theres nothing more i can complain about

**Pull request merged**
